akanami:
  onpropertys:
    component01:
      enable: true
    component02:
      enable: false

  mocker:
    name: akanami
    age: 33
    birth: 2020/06/03
    tags:
      - tag1
      - tag2
      - tag3
    maps:
      key1: value1
      key2: value2
      key3: value3
    maps2: { key1: value1, key2: value2, key3: value3 }