server:
  port: 9041
spring:
  application:
    name: akanami-microservice-hystrix-provider
eureka:
  instance:
    hostname: 127.0.0.1
  client:
    service-url:
      defaultZone: http://127.0.0.1:8091/eureka/