server:
  port: 9502
spring:
  application:
    name: akanami-microservice-gateway-eureka
  cloud:
    discovery:
      locator:
        enabled: true
    gateway:
      routes:
        - id: akanami-microservice-eureka-client-provider    # 路由的id，没有固定规则，但要求唯一，建议配合服务名
          uri: lb://AKANAMI-MICROSERVICE-EUREKA-CLIENT-PROVIDER  #匹配后提供的服务路由地址
          predicates:
            - Path=/**    #断言，路径相匹配的进行路由

#          - id: provider    # 路由的id，没有固定规则，但要求唯一，建议配合服务名
#            uri: http://localhost:8001  #匹配后提供的服务路由地址
#            predicates:
#              - Path=/payment/get/**    #断言，路径相匹配的进行路由

eureka:
  instance:
    hostname: akanami-microservice-gateway-eureka
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://127.0.0.1:8091/eureka/

