package example.mapper;

import example.model.TSysUser;
import java.util.List;

public interface TSysUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_user
     *
     * @mbg.generated Fri Oct 23 15:00:37 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_user
     *
     * @mbg.generated Fri Oct 23 15:00:37 CST 2020
     */
    int insert(TSysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_user
     *
     * @mbg.generated Fri Oct 23 15:00:37 CST 2020
     */
    TSysUser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_user
     *
     * @mbg.generated Fri Oct 23 15:00:37 CST 2020
     */
    List<TSysUser> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_user
     *
     * @mbg.generated Fri Oct 23 15:00:37 CST 2020
     */
    int updateByPrimaryKey(TSysUser record);
}